---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

params:
  SSO_SERVICE_INSTANCE:
  CF_APP_DOMAIN:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_API:
  CF_APP_DOMAIN:

inputs:
- name: support-scripts
- name: sso-hero-app

run:
  path: ./support-scripts/scripts/sso/deploy-sso-hero.sh
