---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

params:
  SSO_SERVICE_TARGET:
  SSO_ADMIN_CLIENT:
  SSO_ADMIN_SECRET:

inputs:
- name: support-scripts

run:
  path: ./support-scripts/scripts/sso/setup-sso-resources.sh
