---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

params:
  OPSMANAGER_HOSTNAME:
  DIRECTOR_IP:
  UAA_LOGIN_ENDPOINT:
  IPD_APP_NAME:

inputs:
- name: support-scripts
- name: saml-idp-app

run:
  path: ./saml-idp-app/scripts/sso/setup-simplesaml.sh
