---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
- name: support-scripts

run:
  path: ./support-scripts/scripts/sso/setup-sso-resources.sh
  args: [{{sso-service-target}}, {{sso-admin-client}}, {{sso-admin-secret}}]
