---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

params:
  OPSMANAGER_HOSTNAME:
  DIRECTOR_IP:
  UAA_LOGIN_ENDPOINT:
  IPD_APP_NAME:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:

inputs:
- name: support-scripts
- name: saml-idp-app

run:
  path: ./support-scripts/scripts/sso/setup-simplesaml.sh
