---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

params:
  SSO_SERVICE_INSTANCE:

inputs:
- name: support-scripts

run:
  path: ./support-scripts/scripts/sso/update-sso-hero-manifest.sh
